server:
  port: 20001
  # 在返回给页面的结果里，把错误信息添加到message里
  error:
    include-message: always

spring:
  application:
    name: coupon-customer-serv
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: 127.0.0.1:8848
        service: coupon-customer-serv
        heart-beat-interval: 5000
        heart-beat-timeout: 15000
        namespace: dev
        group: myGroup
        register-enabled: true
        naming-load-cache-at-start: false
    sentinel:
      transport:
        # sentinel api 端口，默认 8719
        port: 8719
        #doshboard地址
        dashboard: localhost:8080
      datasource:
        #数据源的key，可以自由命名
        yk-flow:
          #指定当前数据源是 Nacos
          nacos:
            #设置Nacos的连接地址、命名空间和Group ID
            secret-key: localhost:8848
            namespace: dev
            groupId: SENTINEL_GROUP
            #设置Nacos中配置文件的命名规则
            dataId: ${spring.application.name}-flow-rules
            #必填的重要字段，指定当前规则类型是“限流”
            rule-type: flow

  #  datasource:
#    # mysql数据源
#    url: jdbc:mysql://127.0.0.1:3306/coupon_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
#    username: root
#    password: 123456
#    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    # 连接池
#    hikari:
#      pool-name: CloudCouponHikari
#      connection-timeout: 5000
#      idle-timeout: 30000
#      maximum-pool-size: 10
#      minimum-idle: 5
#      max-lifetime: 60000
#      auto-commit: true
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: true
    hibernate:
      # 在生产环境全部为none，防止ddl结构被自动执行
      ddl-auto: none
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
    open-in-view: false


logging:
  level:
    top.yk.coupon: debug
