server:
  port: 30000

#spring:
#  application:
#    name: coupon-gateway-serv
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#        heart-beat-interval: 5000
#        heart-beat-timeout: 15000
#        namespace: dev
#        group: myGroup
#
#    gateway:
#      discovery:
#        locator:
#          #允许网关通过服务发现组件，找到其他的微服务
#          enabled: true
#      routes:
#        - id: route-calculation
#          uri: lb://coupon-calculation-serv
#          predicates:
#            - Path=/gateway/calculator/**
#          filters:
#            - StripPrefix=1
#        - id: route-customer
#          uri: lb://coupon-customer-serv
#          predicates:
#            - Path=/gateway/coupon-customer/**
#            - Between=2022-10-12T14:30:33+08:00,2023-12-12T14:30:33+08:00
#          filters:
#            - StripPrefix=1
#        - id: route-template
#          uri: lb://coupon-template-serv
#          predicates:
#            - Path=/gateway/template/**
#          filters:
#            - StripPrefix=1
#    sentinel:
#      transport:
#        port: 8719
#        dashboard: localhost:8080
#      filter:
#        enabled: false
#      scg:
#        fallback:
#          mode: response
#          response-status: 500
#          response-body: '{"code":500,"msg":"网关流量超量！}'