server:
  port: 20001
  # 在返回给页面的结果里，把错误信息添加到message里
  error:
    include-message: always

spring:
  application:
    name: coupon-customer-serv
  datasource:
    # mysql数据源
    url: jdbc:mysql://127.0.0.1:3306/coupon_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接池
    hikari:
      pool-name: CloudCouponHikari
      connection-timeout: 5000
      idle-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
      max-lifetime: 60000
      auto-commit: true
  jpa:
    show-sql: true
    hibernate:
      # 在生产环境全部为none，防止ddl结构被自动执行
      ddl-auto: none
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
    open-in-view: false
  cloud:
    nacos:
      discovery:
        # Nacos 服务器地址，可以配置多个，用，分割
        server-addr: localhost:8848
        # 注册到 Nacos 上的服务名称
        service: coupon-customer-serv
        # 各个微服务向 Nacos 发送心跳的时间间隔，单位是毫秒
        heart-beat-interval: 5000
        # 心跳检测的超时时间，一定要大于 heart-beat-interval
        heart-beat-timeout: 20000
        # 元数据——可以自己随便定制
        metadata:
          myData: chen
        # 命名空间 ID，进行数据隔离
        namespace: dev
        # 两个服务如果要调用，一定要在同一个group
        group: myGroup
        # 服务提供者为true 以下非必须
        register-enabled: true
        # 优先从本地缓存读取服务配置
        naming-load-cache-at-start: false
        username: nacos
        password: nacos
    sleuth:
      sampler:
        probability: 1
        rate: 1000
    zipkin:
      sender:
        type: web
        base-url: http://localhost:9411/
#    openfeign:
#      client:
#        default-config:
#        config:
#          coupon-template-feign-client:
#            connectTimeout: 2000
#            readTimeout: 3000
#            loggerLevel: full
#          coupon-calculation-feign-client:
#            connectTimeout: 2000
#            readTimeout: 3000
#            loggerLevel: full
logging:
  level:
    org.example.coupon: debug
    org.example.coupon.customer.feign.TemplateService: debug
    org.example.coupon.customer.feign.CalculationService: debug

feign:
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 2000
      coupon-template-serv:
        connectTimeout: 1000
        readTimeout: 1500
  #断路器
  circuitbreaker:
    enabled: true